apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: azuredisk
  accessModes:
    - "ReadWriteMany"
  resources:
    limits:
      storage: 5Gi
    requests:
      storage: 1Gi