apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  storageClassName: hostpath
  accessModes:
    - "ReadWriteOnce"
  volumeMode: Filesystem
  resources:
    limits:
      storage: 5Gi
    requests:
      storage: 1Gi