apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
spec:
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      volumes:
        - name: dbvol
          ## The only storageclass available
          hostPath:
            path: "/data"

      containers:
      - name: app4
        image: mysql:5.7
        volumeMounts:
          - name: dbvol
            mountPath: /var/lib/mysql
        envFrom:
          - configMapRef:
              name: dbconfig
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
