apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1

spec:
  ## Maintain ONLY three Revisions in history
  revisionHistoryLimit: 3
  ## Wait for 5 seconds after container is launched
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app-name: app1
  template:
    metadata:
      labels:
        app-name: app1
    spec:
      containers:
        - image: mahendrshinde/myweb:1
          name: web
          resources:
            limits:
              cpu: 200m
              memory: 64Mi    