apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: app1
    version: v1

spec:
  
  containers:
    - name: c1
      image: nginx
      resources:
        limits:
          memory: 500Mi
          cpus: 200m
        requests:
          memory: 100Mi
          cpus: 100m

## Deploy this pod
# $ kubectl delete deploy app1
# $ kubectl apply -f pod1.yml
# $ kubectl get po
# $ kubectl delete -f pod1.yml