apiVersion: v1
kind: Pod
metadata:
  name: secretpod

spec:
  containers:
    - name: c1
      image: nginx
      ## Get all ENVs from secret!
      envFrom:
      - secretRef:
          name: secret1
          